#!/usr/bin/python
import sys, os, glob, shutil

try:
	shutil.rmtree('usb_modeswitch.d')
except:
	pass
os.mkdir('usb_modeswitch.d')
files = glob.glob('usb_modeswitch.d.orig/*')
fmk = open('Android.mk','w')
fmk.write('#### Generated by generate.py\n\n')
fmk.write('LOCAL_PATH := $(call my-dir)\n\n')

fp = open('../usb_modeswitch.mk','w')
fp.write('#### Generated by generate.py\n\n')
fp.write('RODUCT_PACKAGES += \\\n')
fp.write('\tusb_modeswitch \\\n')
fp.write('\tusb_modeswitch.sh \\\n')

for f in files:
	fo = f.replace('.d.orig/','.d/').replace(':','_').replace('=','.').replace('#','')
	shutil.copy(f,fo)
	name = os.path.basename(fo)
	sname = name.split('_')
	f = open(fo,'a+')
	f.write('DefaultVendor=0x%s\n'%sname[0])
	f.write('DefaultProduct=0x%s\n'%sname[1])
	f.flush()
	f.close()
	fmk.write('include $(CLEAR_VARS)\n')
	fmk.write('LOCAL_MODULE := %s\n'%name)
	fmk.write('LOCAL_SRC_FILES := usb_modeswitch.d/%s\n'%name)
	fmk.write('LOCAL_MODULE_CLASS := ETC\n')
	fmk.write('LOCAL_MODULE_PATH := $(TARGET_OUT)/etc/usb_modeswitch.d\n')
	fmk.write('LOCAL_MODULE_TAGS := optional\n')
	fmk.write('include $(BUILD_PREBUILT)\n')
	fmk.write('\n')
	fp.write('\t%s \\\n'%name)
	
fp.write('\n')
fp.flush()
fp.close()	
fmk.flush()
fmk.close()